# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43260622cb20d332fcc95db43d2c33bc274e2826888f0533bd7c3e1cb92cc16cd09eb20131c686d7ff56955fa71bf1cf786da9c8dfaceb819b2712b1e71f32d9

test:
  secret_key_base: 9ba5418bc59c0258f0795efa570de72c8b271b1e9a212a06d47cf0e524d1d403962e26465ddbcc5e3c2a196b010fe525efa95c40a88351226b691f61c7e75bea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
